View and networking
AldrinBahle/Mars-Mission pull request #2
Opened 2020-11-09 05:38 UTC by AldrinBahle

Hi Please review the work I've accomplished thus far.

2020-11-09 10:41 UTC, Sashen943 requested changes

2020-11-09 10:41 UTC, Sashen943 commented on Mars Mission/Mars Mission/Model/WeatherModel.swift
> +struct WeatherAtrr: Codable {
This class should be name Forecast

2020-11-09 10:41 UTC, Sashen943 commented on Mars Mission/Mars Mission/ViewModel/WeatherViewModel.swift
> +            self.view.populateWeather(post.forecasts[0].date ?? "",
Please fix looping here

2020-11-13 01:16 UTC, AldrinBahle commented
<img width="1260" alt="Screenshot 2020-11-09 at 13 53 25" src="https://user-images.githubusercontent.com/20769103/99015839-8137bf80-255e-11eb-9928-426523a49c8c.png">


All the changes requested are now attended.

2020-11-13 10:30 UTC, Sashen943 approved these changes
Some code standard issues like variable naming and commented out code but happy to approve

2020-11-13 11:08 UTC, AldrinBahle commented
Thank you Sir.

2020-11-13 11:08 UTC, AldrinBahle commented
Thank you Sir all comments noted.

2020-11-13 11:09 UTC, merged